### ISSUE TITLE
Unable to parse line 13 as member mapping

### ISSUE THREAD

**Issue by Goooler** [Goooler/diffuse#4]
```
Exception in thread "main" java.lang.IllegalArgumentException: Unable to parse line 13 as member mapping:       # {"id":"com.android.tools.r8.synthesized"}
	at com.jakewharton.diffuse.ApiMapping$Companion.parse(ApiMapping.kt:40)
	at com.jakewharton.diffuse.Aab$Companion.parse(Aab.kt:3)
	at com.jakewharton.diffuse.DiffCommand.run(diffuse.kt:57)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:5266)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:5274)
	at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:281)
	at com.jakewharton.diffuse.Diffuse.main(diffuse.kt:23324)
```

**Comment by Goooler** [comment]
Can't repro for now.
